SELECT [LoanID]
      ,[Amount]
      ,[Loan Months Terms]
      ,[Start Date]
      ,[End Date]
      ,[Interest Rate]
      ,[Customer ID]
      ,[Branch ID]
  FROM [Union_Bank].[dbo].[Loan]
